title: "Gavin Kerr's Research Page"
description: "Liquid bridge dynamics and complex fluids"
theme: jekyll-theme-minimal
show_downloads: false
google_analytics: UA-XXXXXXXXX-X # (optional, for tracking visitors)
